dependencies:
- name: postgresql
  version: 8.0.0
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: postgresql.enabled
- name: redis
  version: 10.4.2
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: elasticsearch
  version: 1.32.2
  repository: https://kubernetes-charts.storage.googleapis.com/
