apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "cds.fullname" . }}-ui
  labels:
    app: {{ template "cds.fullname" . }}-ui
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "cds.fullname" . }}-ui
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: {{ template "cds.fullname" . }}-ui
    spec:
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
      {{- end}}
      {{- end }}
      containers:
      - name: {{ template "cds.fullname" . }}-ui
        image: "{{ .Values.ui.image.registry }}/{{ .Values.ui.image.repository }}:{{ .Values.ui.image.cdstag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        env:
        - name: CDS_CONFIG_FILE
          valueFrom:
            secretKeyRef:
              name: {{ template "cds.fullname" . }}
              key: cds_config_file
        - name: CDS_UI_API_HTTP_URL
          value: http://{{ template "cds.fullname" . }}-api
        - name: CDS_UI_HOOKSURL
          value: {{ template "cds.fullname" . }}-hooks
        - name: CDS_UI_BASEURL
          value: "{{ .Values.ui.baseUrl }}"
        - name: CDS_LOG_LEVEL
          value: "{{ .Values.ui.logLevel }}"
        - name: CDS_UI_NAME
          value: "cds-ui"
        - name: CDS_UI_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ template "cds.fullname" . }}
              key: cds-api_auth_sharedinfratoken
        ports:
        - name: http
          containerPort: 8086
        - name: https
          containerPort: 8086
        command: ["/bin/sh"]
        args: ["-c", "echo $CDS_CONFIG_FILE | base64 -d > config.toml && /app/cds-engine-linux-amd64 start ui --config config.toml"]
        livenessProbe:
{{ toYaml .Values.ui.livenessProbe | indent 10 }}
        readinessProbe:
{{ toYaml .Values.ui.readinessProbe | indent 10 }}
        resources:
{{ toYaml .Values.ui.resources | indent 10 }}
